// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AyCountrySelect: typeof import('@scayle/components')['CountrySelect']
    AyCurrencyBehavior: typeof import('@scayle/components')['CurrencyBehavior']
    AyCurrencyInput: typeof import('@scayle/components')['CurrencyInput']
    AyDashboardList: typeof import('@scayle/components')['DashboardList']
    AyDashboardListItem: typeof import('@scayle/components')['DashboardListItem']
    AyDashboardStatistic: typeof import('@scayle/components')['DashboardStatistic']
    AyInput: typeof import('@scayle/components')['Input']
    AyModal: typeof import('@scayle/components')['Modal']
    AyOffCanvas: typeof import('@scayle/components')['OffCanvas']
    AyOption: typeof import('@scayle/components')['Option']
    AyPaginationLayout: typeof import('@scayle/components')['PaginationLayout']
    AySelect: typeof import('@scayle/components')['Select']
    AySpinner: typeof import('@scayle/components')['Spinner']
    AyTab: typeof import('@scayle/components')['Tab']
    AyTabs: typeof import('@scayle/components')['Tabs']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IconArrowRight: typeof import('~icons/panel/arrow-right')['default']
    IconFilter: typeof import('~icons/panel/filter')['default']
    IconImageSingle: typeof import('~icons/panel/image-single')['default']
    IconMoney: typeof import('~icons/panel/money')['default']
    IconParcel: typeof import('~icons/panel/parcel')['default']
    IconQuestionFill: typeof import('~icons/panel/question-fill')['default']
    IconShirt: typeof import('~icons/panel/shirt')['default']
    IconTrash: typeof import('~icons/panel/trash')['default']
    IconUser: typeof import('~icons/panel/user')['default']
    LabeledComponent: typeof import('~icons/la/beled-component')['default']
    LabeledInput: typeof import('~icons/la/beled-input')['default']
    LabelInput: typeof import('~icons/la/bel-input')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
